package restaurant.GUI;

import restaurant.system.RestaurantSystem;

/**
 *
 * @author tai
 */
public class CheckInPanel extends javax.swing.JPanel {


    public CheckInPanel(RestaurantSystem restaurantSystem) 
    {
    	this.restaurantSytem = restaurantSytem;
        setUpPanel();
        addItemsToTableList();
    }
    
    private void addItemsToTableList()
    {
        tableList.add(new javax.swing.JLabel("test"));
        tableList.remove(0);
        tableList.removeAll();

   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void setUpPanel() {

        tableInfo = new javax.swing.JPanel();
        tableNameLabel = new java.awt.Label();
        tableCapLabel = new java.awt.Label();
        tableOccupiedLabel = new java.awt.Label();
        tabelListPanel = new java.awt.Panel();
        tableControlPanel = new java.awt.Panel();
        tableListScrollPane = new javax.swing.JScrollPane();
        tableList = new javax.swing.JList();
        setOccupiiedJBut = new javax.swing.JButton();
        occupiedSizeSpinner = new javax.swing.JSpinner();
        setUnoccupiedJBut = new javax.swing.JButton();
        waitListLabel = new java.awt.Label();
        waitListPanel = new java.awt.Panel();
        waitListControlPanel = new java.awt.Panel();
        jTextField1 = new javax.swing.JTextField();
        partySizeSpinner = new javax.swing.JSpinner();
        paryNameLabel = new javax.swing.JLabel();
        partySizeLabel = new javax.swing.JLabel();
        assignTableBut = new javax.swing.JButton();
        addBut = new javax.swing.JButton();
        remBut = new javax.swing.JButton();
        waitListScrollPane = new javax.swing.JScrollPane();
        waitList = new javax.swing.JList();

        

        tableInfo.setForeground(java.awt.SystemColor.windowBorder);
        tableNameLabel.setEnabled(false);
        tableNameLabel.setText("Name");

        tableCapLabel.setName("Capacity"); // NOI18N
        tableCapLabel.setText("Capacity");

        tableOccupiedLabel.setEnabled(false);
        tableOccupiedLabel.setName(""); // NOI18N
        tableOccupiedLabel.setText("Occupied");

        javax.swing.GroupLayout tableControlPanelLayout = new javax.swing.GroupLayout(tableControlPanel);
        tableControlPanel.setLayout(tableControlPanelLayout);
        tableControlPanelLayout.setHorizontalGroup(
            tableControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        tableControlPanelLayout.setVerticalGroup(
            tableControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 87, Short.MAX_VALUE)
        );

        tableList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        tableList.setVisibleRowCount(-1);
        tableListScrollPane.setViewportView(tableList);

        setOccupiiedJBut.setText("Set occupied");

        setUnoccupiedJBut.setText("Set unoccupied");
        setUnoccupiedJBut.setToolTipText("");

        javax.swing.GroupLayout tabelListPanelLayout = new javax.swing.GroupLayout(tabelListPanel);
        tabelListPanel.setLayout(tabelListPanelLayout);
        tabelListPanelLayout.setHorizontalGroup(
            tabelListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabelListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabelListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabelListPanelLayout.createSequentialGroup()
                        .addComponent(tableListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(tabelListPanelLayout.createSequentialGroup()
                        .addComponent(setOccupiiedJBut, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(occupiedSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setUnoccupiedJBut, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tableControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tabelListPanelLayout.setVerticalGroup(
            tabelListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabelListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabelListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabelListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(setOccupiiedJBut)
                        .addComponent(occupiedSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(setUnoccupiedJBut)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tableInfoLayout = new javax.swing.GroupLayout(tableInfo);
        tableInfo.setLayout(tableInfoLayout);
        tableInfoLayout.setHorizontalGroup(
            tableInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableInfoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(tableNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tableCapLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(tableOccupiedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(tableInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabelListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tableInfoLayout.setVerticalGroup(
            tableInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tableInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableOccupiedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tableNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tableCapLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(tabelListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        tableNameLabel.getAccessibleContext().setAccessibleName("tableNameLabel");
        tableCapLabel.getAccessibleContext().setAccessibleDescription("Capacity");

        waitListLabel.setText("Wait List");

        jTextField1.setText("name");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        paryNameLabel.setText("Name:");

        partySizeLabel.setText("Party size:");

        assignTableBut.setText("Assign Table");

        addBut.setText("Add");
        addBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButActionPerformed(evt);
            }
        });

        remBut.setText("Remove");

        javax.swing.GroupLayout waitListControlPanelLayout = new javax.swing.GroupLayout(waitListControlPanel);
        waitListControlPanel.setLayout(waitListControlPanelLayout);
        waitListControlPanelLayout.setHorizontalGroup(
            waitListControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(waitListControlPanelLayout.createSequentialGroup()
                .addGroup(waitListControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(waitListControlPanelLayout.createSequentialGroup()
                        .addComponent(paryNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(partySizeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(partySizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(waitListControlPanelLayout.createSequentialGroup()
                        .addComponent(assignTableBut, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addBut, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(remBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        waitListControlPanelLayout.setVerticalGroup(
            waitListControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(waitListControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(waitListControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paryNameLabel)
                    .addComponent(partySizeLabel)
                    .addComponent(partySizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(waitListControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignTableBut)
                    .addComponent(addBut)
                    .addComponent(remBut))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        waitList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        waitList.setVisibleRowCount(-1);
        waitListScrollPane.setViewportView(waitList);

        javax.swing.GroupLayout waitListPanelLayout = new javax.swing.GroupLayout(waitListPanel);
        waitListPanel.setLayout(waitListPanelLayout);
        waitListPanelLayout.setHorizontalGroup(
            waitListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(waitListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(waitListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(waitListControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(waitListPanelLayout.createSequentialGroup()
                        .addComponent(waitListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        waitListPanelLayout.setVerticalGroup(
            waitListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(waitListPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(waitListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waitListControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(waitListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(waitListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(355, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(waitListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waitListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        waitListLabel.getAccessibleContext().setAccessibleName("WaitList");


    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void addButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckInPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckInPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckInPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckInPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

      
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBut;
    private javax.swing.JButton assignTableBut;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JSpinner occupiedSizeSpinner;
    private javax.swing.JLabel partySizeLabel;
    private javax.swing.JSpinner partySizeSpinner;
    private javax.swing.JLabel paryNameLabel;
    private javax.swing.JButton remBut;
    private javax.swing.JButton setOccupiiedJBut;
    private javax.swing.JButton setUnoccupiedJBut;
    private java.awt.Panel tabelListPanel;
    private java.awt.Label tableCapLabel;
    private java.awt.Panel tableControlPanel;
    private javax.swing.JPanel tableInfo;
    private javax.swing.JList tableList;
    private javax.swing.JScrollPane tableListScrollPane;
    private java.awt.Label tableNameLabel;
    private java.awt.Label tableOccupiedLabel;
    private javax.swing.JList waitList;
    private java.awt.Panel waitListControlPanel;
    private java.awt.Label waitListLabel;
    private java.awt.Panel waitListPanel;
    private javax.swing.JScrollPane waitListScrollPane;
    
    private RestaurantSystem restaurantSytem;
}
////////